version: "3.4"

networks:
  kis:
    external:
      name: kis.localhost

services:
  terraspace-demo:
    container_name: terraspace-demo
    image: boltops/terraspace:ubuntu
    command:
      - -c
      - -l
      - "sleep infinity"
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      default:
      kis:
    volumes:
      - .:/opt/demo
